name: biometric_auth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-15.0.dev <4.0.0'

dependencies:
  device_info_plus: ^9.0.3
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  http: ^1.1.0
  local_auth: ^2.1.7
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
